server:
  servlet:
    context-path: /api/v1/
  error:
    include-exception: true
    include-message: always
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: "Spendly"
  data:
    mongodb:
      uri: mongodb://localhost:27017/spendly

jwt:
  secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
  expiration: 86400000  # 24 hours in milliseconds

exchange-rate:
  api-key: your_exchange_rate_api_key
  url: https://api.exchangeratesapi.io/v1/latest
  symbols: USD,LKR,INR
  update-cron: "0 0 * * * *"  # daily at midnight

logging:
  level:
    root: INFO
