server:
  servlet:
    context-path: /api/v1/
  error:
    include-exception: true
    include-message: always
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: "Spendly"
  data:
    mongodb:
      uri: mongodb://localhost:27017/spendly

  mail:
    host: smtp.gmail.com
    port: 587
    username: prashansamarathunge@gmail.com
    password: vgss jqsh ytgd aigv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
  expiration: 86400000  # 24 hours in milliseconds

exchange-rate:
  api-key: 41560c62cc1a7665b4e760561389c699
  url: https://api.exchangeratesapi.io/v1/latest
  symbols: USD,LKR,INR
  update-cron: "0 0 * * * *"  # daily at midnight

logging:
  level:
    root: INFO

app:
  verification:
    base-url: "http://localhost:8080/api/v1"